name: samba
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy>=1.24
  - tqdm>=4.65
  - pyyaml>=6.0
  - pip
  - pip:
      - transformers>=4.39
      - datasets>=2.14
      - tokenizers>=0.15
      - mamba-ssm>=1.0
      - causal-conv1d>=1.0
      - triton>=2.0
      - wandb>=0.15
      - ipython
      - jupyter
