name: samba
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy>=1.24.0
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - pip
  - pip:
      - transformers>=4.39.0
      - datasets>=2.14.0
      - tokenizers>=0.15.0
      - wandb>=0.15.0
      - ipython
      - jupyter
